### ISSUE TITLE
Broken with Jekyll 3

### ISSUE THREAD

**Issue by bobgle** [liaohuqiu/jekyll-multiple-languages#11]
It isn't working anymore since Post got renamed to Document, even with the rename some methods aren't valid anymore (Process). A shame since I'd love this.

**Comment by liaohuqiu** [comment]
which version

**Comment by bobgle** [comment]
v3.0.0

**Comment by suzel** [comment]
jekyll build --trace
Configuration file: /Users/suzel/Desktop/ws/_config.yml
/usr/local/lib/ruby/gems/2.2.0/gems/jekyll-multiple-languages-1.0.11/lib/jekyll-multiple-languages.rb:234:in `<class:Post>': undefined method `url' for class `Jekyll::Post' (NameError)
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-multiple-languages-1.0.11/lib/jekyll-multiple-languages.rb:224:in `<module:Jekyll>'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-multiple-languages-1.0.11/lib/jekyll-multiple-languages.rb:4:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:30:in `require'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:30:in `block in require_gems'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:27:in `each'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:27:in `require_gems'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:19:in `conscientious_require'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/site.rb:97:in `setup'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/site.rb:49:in `initialize'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:30:in `new'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:30:in `process'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/bin/jekyll:17:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'
