### ISSUE TITLE
page.next and page.previous get all languages

### ISSUE THREAD

**Issue by cbergmann** [liaohuqiu/jekyll-multiple-languages#5]
Hi,

first thanks for the good module. It works really well.

I use page.next and page.previous in my templates to link between posts.
When I activate this plugin these fields point to all languages.
So when I am on a german page page.next might be a english page and from there page.next might be a spanish page. 
Is it possible to get the next page of the same language?

best regards
Clemens

**Comment by liaohuqiu** [comment]
Thank you for you contribution, 1.0.7 has been pushed to rubygems.
