### ISSUE TITLE
Neither site.posts_by_language or site.pages_by_language are defined

### ISSUE THREAD

**Issue by dexpota** [liaohuqiu/jekyll-multiple-languages#8]
When I try using `post_by_language` or `pages_by_language` inside a template like this `{{site.posts_by_language }}` or inside a for-loop, I cannot get any value. I'm using Jekyll 2.5.3 and Ruby 2.0.

I've just started using Jekyll and I've never programmed in Ruby. I tried to search for the bug and I changed the method `site_payload` inside Site class, and now it works. This is the new version

```ruby
alias :site_payload_org :site_payload
def site_payload
      h = site_payload_org
      payload = h["site"]
      payload = payload.merge({
       "posts_by_language" => self.posts_by_language,
       "pages_by_language" => self.pages_by_language,
      })
      h["site"] = payload
      h
```

**Comment by liaohuqiu** [comment]
Thank you for your feedback. I'll take a look at this version.

**Comment by NoahDragon** [comment]
I have the same problem while using Ruby 1.9.3, but it's under Octopress 3.0 (Assuming it is the latest jekyll 2.5.3).

**Comment by NoahDragon** [comment]
I just would like to follow up this. Is dexpota's method right hotfix for this issue?

**Comment by dexpota** [comment]
The change I made is working in my case. I am using Jekyll 2.5.3, Ruby 2.1.2p95, with the last version of this plugin.

**Comment by kuka** [comment]
https://github.com/liaohuqiu/jekyll-multiple-languages/pull/9
